language: go
go_import_path: github.com/kevinburke/go-types

os: linux
dist: trusty

sudo: required

before_script:
     - make install-travis

script:
  - make ci

cache:
  directories:
    - $HOME/.bzrepos
    - $HOME/.cache/bazel
